export type Projekt = {
  slug: string;
  title: string;
  ort: string;
  kvm: number;
  typ: string;
  beskrivning: string;
  material: string;
  år: number;
  taggar: string[];
  image: string;
  images: string[];
  imageBefore?: string;
};

export const projekt: Projekt[] = [
  {
    slug: "fagerasen-vrena",
    title: "Fageråsen — Vrena",
    ort: "Nyköping",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Fageråsen i Vrena. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Nyköping"],
    image: "/images/projekt/fagerasen-vrena.jpg",
    images: ["/images/projekt/fagerasen-vrena.jpg", "/images/projekt/fagerasen-vrena-2.jpg", "/images/projekt/fagerasen-vrena-3.jpg"],
  },
  {
    slug: "plommonvagen-bromma",
    title: "Plommonvägen — Bromma",
    ort: "Stockholm",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Plommonvägen i Bromma. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2024,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/plommonvagen-bromma.jpg",
    images: ["/images/projekt/plommonvagen-bromma.jpg", "/images/projekt/plommonvagen-bromma-2.jpg", "/images/projekt/plommonvagen-bromma-3.jpg", "/images/projekt/plommonvagen-bromma-4.jpg", "/images/projekt/plommonvagen-bromma-5.jpg", "/images/projekt/plommonvagen-bromma-6.jpg", "/images/projekt/plommonvagen-bromma-7.jpg", "/images/projekt/plommonvagen-bromma-8.jpg", "/images/projekt/plommonvagen-bromma-9.jpg", "/images/projekt/plommonvagen-bromma-10.jpg"],
  },
  {
    slug: "hakevagen-djursholm",
    title: "Hakevägen — Djursholm",
    ort: "Danderyd",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Hakevägen i Djursholm. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Danderyd"],
    image: "/images/projekt/hakevagen-djursholm.jpg",
    images: ["/images/projekt/hakevagen-djursholm.jpg", "/images/projekt/hakevagen-djursholm-2.jpg", "/images/projekt/hakevagen-djursholm-3.jpg", "/images/projekt/hakevagen-djursholm-4.jpg", "/images/projekt/hakevagen-djursholm-5.jpg", "/images/projekt/hakevagen-djursholm-6.jpg", "/images/projekt/hakevagen-djursholm-7.jpg", "/images/projekt/hakevagen-djursholm-8.jpg", "/images/projekt/hakevagen-djursholm-9.jpg", "/images/projekt/hakevagen-djursholm-10.jpg", "/images/projekt/hakevagen-djursholm-11.jpg", "/images/projekt/hakevagen-djursholm-12.jpg"],
  },
  {
    slug: "timmerbacken-tumba",
    title: "Timmerbacken — Tumba",
    ort: "Botkyrka",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Timmerbacken i Tumba. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Botkyrka"],
    image: "/images/projekt/timmerbacken-tumba.jpg",
    images: ["/images/projekt/timmerbacken-tumba.jpg", "/images/projekt/timmerbacken-tumba-2.jpg", "/images/projekt/timmerbacken-tumba-3.jpg", "/images/projekt/timmerbacken-tumba-4.jpg", "/images/projekt/timmerbacken-tumba-5.jpg", "/images/projekt/timmerbacken-tumba-6.jpg", "/images/projekt/timmerbacken-tumba-7.jpg", "/images/projekt/timmerbacken-tumba-8.jpg", "/images/projekt/timmerbacken-tumba-9.jpg", "/images/projekt/timmerbacken-tumba-10.jpg", "/images/projekt/timmerbacken-tumba-11.jpg", "/images/projekt/timmerbacken-tumba-12.jpg"],
  },
  {
    slug: "skovelvagen-alvsjo",
    title: "Skovelvägen — Älvsjö",
    ort: "Stockholm",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Skovelvägen i Älvsjö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2023,
    taggar: ["Plåttak", "Stockholm"],
    image: "/images/projekt/skovelvagen-alvsjo.jpg",
    images: ["/images/projekt/skovelvagen-alvsjo.jpg", "/images/projekt/skovelvagen-alvsjo-2.jpg", "/images/projekt/skovelvagen-alvsjo-3.jpg", "/images/projekt/skovelvagen-alvsjo-4.jpg"],
  },
  {
    slug: "solfagravagen-huddinge",
    title: "Solfagravägen — Huddinge",
    ort: "Huddinge",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Solfagravägen i Huddinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Huddinge"],
    image: "/images/projekt/solfagravagen-huddinge.jpg",
    images: ["/images/projekt/solfagravagen-huddinge.jpg", "/images/projekt/solfagravagen-huddinge-2.jpg", "/images/projekt/solfagravagen-huddinge-3.jpg", "/images/projekt/solfagravagen-huddinge-4.jpg", "/images/projekt/solfagravagen-huddinge-5.jpg", "/images/projekt/solfagravagen-huddinge-6.jpg"],
  },
  {
    slug: "sorgardsvagen-bromma",
    title: "Sörgårdsvägen — Bromma",
    ort: "Stockholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Sörgårdsvägen i Bromma. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/sorgardsvagen-bromma.jpg",
    images: ["/images/projekt/sorgardsvagen-bromma.jpg", "/images/projekt/sorgardsvagen-bromma-2.jpg", "/images/projekt/sorgardsvagen-bromma-3.jpg", "/images/projekt/sorgardsvagen-bromma-4.jpg", "/images/projekt/sorgardsvagen-bromma-5.jpg", "/images/projekt/sorgardsvagen-bromma-6.jpg"],
  },
  {
    slug: "kastanjetunet-lidingo",
    title: "Kastanjetunet — Lidingö",
    ort: "Lidingö",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Kastanjetunet i Lidingö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2022,
    taggar: ["Betongtak", "Lidingö"],
    image: "/images/projekt/kastanjetunet-lidingo.jpg",
    images: ["/images/projekt/kastanjetunet-lidingo.jpg", "/images/projekt/kastanjetunet-lidingo-2.jpg", "/images/projekt/kastanjetunet-lidingo-3.jpg", "/images/projekt/kastanjetunet-lidingo-4.jpg", "/images/projekt/kastanjetunet-lidingo-5.jpg", "/images/projekt/kastanjetunet-lidingo-6.jpg", "/images/projekt/kastanjetunet-lidingo-7.jpg", "/images/projekt/kastanjetunet-lidingo-8.jpg", "/images/projekt/kastanjetunet-lidingo-9.jpg", "/images/projekt/kastanjetunet-lidingo-10.jpg", "/images/projekt/kastanjetunet-lidingo-11.jpg", "/images/projekt/kastanjetunet-lidingo-12.jpg"],
  },
  {
    slug: "prastgardsvagen-tumba",
    title: "Prästgårdsvägen — Tumba",
    ort: "Botkyrka",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Prästgårdsvägen i Tumba. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Botkyrka"],
    image: "/images/projekt/prastgardsvagen-tumba.jpg",
    images: ["/images/projekt/prastgardsvagen-tumba.jpg", "/images/projekt/prastgardsvagen-tumba-2.jpg", "/images/projekt/prastgardsvagen-tumba-3.jpg", "/images/projekt/prastgardsvagen-tumba-4.jpg"],
  },
  {
    slug: "skacklingevagen-tumba",
    title: "Skäcklingevägen — Tumba",
    ort: "Botkyrka",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Skäcklingevägen i Tumba. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2021,
    taggar: ["Plåttak", "Botkyrka"],
    image: "/images/projekt/skacklingevagen-tumba.jpg",
    images: ["/images/projekt/skacklingevagen-tumba.jpg"],
  },
  {
    slug: "skrattmasvagen-farsta",
    title: "Skrattmåsvägen — Farsta",
    ort: "Stockholm",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Skrattmåsvägen i Farsta. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2021,
    taggar: ["Betongtak", "Stockholm"],
    image: "/images/projekt/skrattmasvagen-farsta.jpg",
    images: ["/images/projekt/skrattmasvagen-farsta.jpg", "/images/projekt/skrattmasvagen-farsta-2.jpg", "/images/projekt/skrattmasvagen-farsta-3.jpg", "/images/projekt/skrattmasvagen-farsta-4.jpg"],
  },
  {
    slug: "vartavagen-taby",
    title: "Värtavägen — Täby",
    ort: "Täby",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Värtavägen i Täby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2021,
    taggar: ["Tegeltak", "Täby"],
    image: "/images/projekt/vartavagen-taby.jpg",
    images: ["/images/projekt/vartavagen-taby.jpg"],
  },
  {
    slug: "nytorpsvagen-koping",
    title: "Nytorpsvägen — Köping",
    ort: "Köping",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Nytorpsvägen i Köping. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2020,
    taggar: ["Betongtak", "Köping"],
    image: "/images/projekt/nytorpsvagen-koping.jpg",
    images: ["/images/projekt/nytorpsvagen-koping.jpg", "/images/projekt/nytorpsvagen-koping-2.jpg", "/images/projekt/nytorpsvagen-koping-3.jpg", "/images/projekt/nytorpsvagen-koping-4.jpg", "/images/projekt/nytorpsvagen-koping-5.jpg", "/images/projekt/nytorpsvagen-koping-6.jpg"],
  },
  {
    slug: "norrangsvagen-huddinge",
    title: "Norrängsvägen — Huddinge",
    ort: "Huddinge",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Norrängsvägen i Huddinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2020,
    taggar: ["Tegeltak", "Huddinge"],
    image: "/images/projekt/norrangsvagen-huddinge.jpg",
    images: ["/images/projekt/norrangsvagen-huddinge.jpg", "/images/projekt/norrangsvagen-huddinge-2.jpg", "/images/projekt/norrangsvagen-huddinge-3.jpg", "/images/projekt/norrangsvagen-huddinge-4.jpg"],
  },
  {
    slug: "alstromervagen-skarholmen",
    title: "Alströmervägen — Skärholmen",
    ort: "Stockholm",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Alströmervägen i Skärholmen. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2024,
    taggar: ["Plåttak", "Stockholm"],
    image: "/images/projekt/alstromervagen-skarholmen.jpg",
    images: ["/images/projekt/alstromervagen-skarholmen.jpg", "/images/projekt/alstromervagen-skarholmen-2.jpg", "/images/projekt/alstromervagen-skarholmen-3.jpg", "/images/projekt/alstromervagen-skarholmen-4.jpg"],
  },
  {
    slug: "taby-taby",
    title: "Täby",
    ort: "Täby",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Täby i Täby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Täby"],
    image: "/images/projekt/taby-taby.jpg",
    images: ["/images/projekt/taby-taby.jpg", "/images/projekt/taby-taby-2.jpg", "/images/projekt/taby-taby-3.jpg", "/images/projekt/taby-taby-4.jpg", "/images/projekt/taby-taby-5.jpg", "/images/projekt/taby-taby-6.jpg", "/images/projekt/taby-taby-7.jpg", "/images/projekt/taby-taby-8.jpg", "/images/projekt/taby-taby-9.jpg", "/images/projekt/taby-taby-10.jpg", "/images/projekt/taby-taby-11.jpg", "/images/projekt/taby-taby-12.jpg", "/images/projekt/taby-taby-13.jpg"],
  },
  {
    slug: "sollentuna-sollentuna",
    title: "Sollentuna",
    ort: "Sollentuna",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Sollentuna i Sollentuna. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2024,
    taggar: ["Tegeltak", "Sollentuna"],
    image: "/images/projekt/sollentuna-sollentuna.jpg",
    images: ["/images/projekt/sollentuna-sollentuna.jpg", "/images/projekt/sollentuna-sollentuna-2.jpg", "/images/projekt/sollentuna-sollentuna-3.jpg", "/images/projekt/sollentuna-sollentuna-4.jpg"],
  },
  {
    slug: "huddinge-huddinge",
    title: "Huddinge",
    ort: "Huddinge",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Huddinge i Huddinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Huddinge"],
    image: "/images/projekt/huddinge-huddinge.jpg",
    images: ["/images/projekt/huddinge-huddinge.jpg", "/images/projekt/huddinge-huddinge-2.jpg", "/images/projekt/huddinge-huddinge-3.jpg", "/images/projekt/huddinge-huddinge-4.jpg", "/images/projekt/huddinge-huddinge-5.jpg", "/images/projekt/huddinge-huddinge-6.jpg", "/images/projekt/huddinge-huddinge-7.jpg", "/images/projekt/huddinge-huddinge-8.jpg", "/images/projekt/huddinge-huddinge-9.jpg"],
  },
  {
    slug: "bromma-bromma",
    title: "Bromma",
    ort: "Stockholm",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Bromma i Bromma. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/bromma-bromma.jpg",
    images: ["/images/projekt/bromma-bromma.jpg", "/images/projekt/bromma-bromma-2.jpg", "/images/projekt/bromma-bromma-3.jpg", "/images/projekt/bromma-bromma-4.jpg", "/images/projekt/bromma-bromma-5.jpg", "/images/projekt/bromma-bromma-6.jpg"],
  },
  {
    slug: "upplands-vasby-upplands-vasby",
    title: "Upplands Väsby",
    ort: "Upplands Väsby",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Upplands Väsby i Upplands Väsby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2023,
    taggar: ["Plåttak", "Upplands Väsby"],
    image: "/images/projekt/upplands-vasby-upplands-vasby.jpg",
    images: ["/images/projekt/upplands-vasby-upplands-vasby.jpg", "/images/projekt/upplands-vasby-upplands-vasby-2.jpg", "/images/projekt/upplands-vasby-upplands-vasby-3.jpg", "/images/projekt/upplands-vasby-upplands-vasby-4.jpg", "/images/projekt/upplands-vasby-upplands-vasby-5.jpg", "/images/projekt/upplands-vasby-upplands-vasby-6.jpg", "/images/projekt/upplands-vasby-upplands-vasby-7.jpg", "/images/projekt/upplands-vasby-upplands-vasby-8.jpg", "/images/projekt/upplands-vasby-upplands-vasby-9.jpg", "/images/projekt/upplands-vasby-upplands-vasby-10.jpg", "/images/projekt/upplands-vasby-upplands-vasby-11.jpg", "/images/projekt/upplands-vasby-upplands-vasby-12.jpg", "/images/projekt/upplands-vasby-upplands-vasby-13.jpg", "/images/projekt/upplands-vasby-upplands-vasby-14.jpg", "/images/projekt/upplands-vasby-upplands-vasby-15.jpg", "/images/projekt/upplands-vasby-upplands-vasby-16.jpg", "/images/projekt/upplands-vasby-upplands-vasby-17.jpg", "/images/projekt/upplands-vasby-upplands-vasby-18.jpg", "/images/projekt/upplands-vasby-upplands-vasby-19.jpg", "/images/projekt/upplands-vasby-upplands-vasby-20.jpg", "/images/projekt/upplands-vasby-upplands-vasby-21.jpg", "/images/projekt/upplands-vasby-upplands-vasby-22.jpg", "/images/projekt/upplands-vasby-upplands-vasby-23.jpg", "/images/projekt/upplands-vasby-upplands-vasby-24.jpg", "/images/projekt/upplands-vasby-upplands-vasby-25.jpg", "/images/projekt/upplands-vasby-upplands-vasby-26.jpg", "/images/projekt/upplands-vasby-upplands-vasby-27.jpg"],
  },
  {
    slug: "nacka-nacka",
    title: "Nacka",
    ort: "Nacka",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Nacka i Nacka. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2022,
    taggar: ["Betongtak", "Nacka"],
    image: "/images/projekt/nacka-nacka.jpg",
    images: ["/images/projekt/nacka-nacka.jpg", "/images/projekt/nacka-nacka-2.jpg", "/images/projekt/nacka-nacka-3.jpg", "/images/projekt/nacka-nacka-4.jpg", "/images/projekt/nacka-nacka-5.jpg", "/images/projekt/nacka-nacka-6.jpg"],
  },
  {
    slug: "lidingo-lidingo",
    title: "Lidingö",
    ort: "Lidingö",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Lidingö i Lidingö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Lidingö"],
    image: "/images/projekt/lidingo-lidingo.jpg",
    images: ["/images/projekt/lidingo-lidingo.jpg", "/images/projekt/lidingo-lidingo-2.jpg", "/images/projekt/lidingo-lidingo-3.jpg", "/images/projekt/lidingo-lidingo-4.jpg"],
  },
  {
    slug: "enskede-enskede",
    title: "Enskede",
    ort: "Stockholm",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Enskede i Enskede. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2022,
    taggar: ["Betongtak", "Stockholm"],
    image: "/images/projekt/enskede-enskede.jpg",
    images: ["/images/projekt/enskede-enskede.jpg", "/images/projekt/enskede-enskede-2.jpg", "/images/projekt/enskede-enskede-3.jpg", "/images/projekt/enskede-enskede-4.jpg", "/images/projekt/enskede-enskede-5.jpg", "/images/projekt/enskede-enskede-6.jpg", "/images/projekt/enskede-enskede-7.jpg", "/images/projekt/enskede-enskede-8.jpg"],
  },
  {
    slug: "staket-jarfalla",
    title: "Stäket — Järfälla",
    ort: "Järfälla",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Stäket i Järfälla. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2021,
    taggar: ["Tegeltak", "Järfälla"],
    image: "/images/projekt/staket-jarfalla.jpg",
    images: ["/images/projekt/staket-jarfalla.jpg", "/images/projekt/staket-jarfalla-2.jpg", "/images/projekt/staket-jarfalla-3.jpg"],
  },
  {
    slug: "vallentuna-vallentuna",
    title: "Vallentuna",
    ort: "Vallentuna",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Vallentuna i Vallentuna. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2021,
    taggar: ["Plåttak", "Vallentuna"],
    image: "/images/projekt/vallentuna-vallentuna.jpg",
    images: ["/images/projekt/vallentuna-vallentuna.jpg", "/images/projekt/vallentuna-vallentuna-2.jpg", "/images/projekt/vallentuna-vallentuna-3.jpg", "/images/projekt/vallentuna-vallentuna-4.jpg", "/images/projekt/vallentuna-vallentuna-5.jpg", "/images/projekt/vallentuna-vallentuna-6.jpg"],
  },
  {
    slug: "jarfalla-jarfalla",
    title: "Järfälla",
    ort: "Järfälla",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Järfälla i Järfälla. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2021,
    taggar: ["Betongtak", "Järfälla"],
    image: "/images/projekt/jarfalla-jarfalla.jpg",
    images: ["/images/projekt/jarfalla-jarfalla.jpg", "/images/projekt/jarfalla-jarfalla-2.jpg", "/images/projekt/jarfalla-jarfalla-3.jpg", "/images/projekt/jarfalla-jarfalla-4.jpg", "/images/projekt/jarfalla-jarfalla-5.jpg", "/images/projekt/jarfalla-jarfalla-6.jpg", "/images/projekt/jarfalla-jarfalla-7.jpg", "/images/projekt/jarfalla-jarfalla-8.jpg", "/images/projekt/jarfalla-jarfalla-9.jpg", "/images/projekt/jarfalla-jarfalla-10.jpg", "/images/projekt/jarfalla-jarfalla-11.jpg", "/images/projekt/jarfalla-jarfalla-12.jpg"],
  },
  {
    slug: "kungsholmen-kungsholmen",
    title: "Kungsholmen",
    ort: "Stockholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Kungsholmen i Kungsholmen. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2020,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/kungsholmen-kungsholmen.jpg",
    images: ["/images/projekt/kungsholmen-kungsholmen.jpg", "/images/projekt/kungsholmen-kungsholmen-2.jpg", "/images/projekt/kungsholmen-kungsholmen-3.jpg", "/images/projekt/kungsholmen-kungsholmen-4.jpg", "/images/projekt/kungsholmen-kungsholmen-5.jpg", "/images/projekt/kungsholmen-kungsholmen-6.jpg", "/images/projekt/kungsholmen-kungsholmen-7.jpg", "/images/projekt/kungsholmen-kungsholmen-8.jpg", "/images/projekt/kungsholmen-kungsholmen-9.jpg", "/images/projekt/kungsholmen-kungsholmen-10.jpg", "/images/projekt/kungsholmen-kungsholmen-11.jpg", "/images/projekt/kungsholmen-kungsholmen-12.jpg"],
  },
  {
    slug: "nykoping-nykoping",
    title: "Nyköping",
    ort: "Nyköping",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Nyköping i Nyköping. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2020,
    taggar: ["Betongtak", "Nyköping"],
    image: "/images/projekt/nykoping-nykoping.jpg",
    images: ["/images/projekt/nykoping-nykoping.jpg", "/images/projekt/nykoping-nykoping-2.jpg", "/images/projekt/nykoping-nykoping-3.jpg"],
  },
  {
    slug: "farsta-farsta",
    title: "Farsta",
    ort: "Stockholm",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Farsta i Farsta. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2024,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/farsta-farsta.jpg",
    images: ["/images/projekt/farsta-farsta.jpg", "/images/projekt/farsta-farsta-2.jpg", "/images/projekt/farsta-farsta-3.jpg"],
  },
  {
    slug: "grodinge-grodinge",
    title: "Grödinge",
    ort: "Botkyrka",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Grödinge i Grödinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2024,
    taggar: ["Plåttak", "Botkyrka"],
    image: "/images/projekt/grodinge-grodinge.jpg",
    images: ["/images/projekt/grodinge-grodinge.jpg", "/images/projekt/grodinge-grodinge-2.jpg", "/images/projekt/grodinge-grodinge-3.jpg"],
  },
  {
    slug: "varmdo-varmdo",
    title: "Värmdö",
    ort: "Värmdö",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Värmdö i Värmdö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Värmdö"],
    image: "/images/projekt/varmdo-varmdo.jpg",
    images: ["/images/projekt/varmdo-varmdo.jpg", "/images/projekt/varmdo-varmdo-2.jpg", "/images/projekt/varmdo-varmdo-3.jpg", "/images/projekt/varmdo-varmdo-4.jpg", "/images/projekt/varmdo-varmdo-5.jpg", "/images/projekt/varmdo-varmdo-6.jpg"],
  },
  {
    slug: "saltsjo-boo-saltsjo-boo",
    title: "Saltsjö-Boo",
    ort: "Nacka",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Saltsjö-Boo i Saltsjö-Boo. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Nacka"],
    image: "/images/projekt/saltsjo-boo-saltsjo-boo.jpg",
    images: ["/images/projekt/saltsjo-boo-saltsjo-boo.jpg", "/images/projekt/saltsjo-boo-saltsjo-boo-2.jpg", "/images/projekt/saltsjo-boo-saltsjo-boo-3.jpg", "/images/projekt/saltsjo-boo-saltsjo-boo-4.jpg", "/images/projekt/saltsjo-boo-saltsjo-boo-5.jpg", "/images/projekt/saltsjo-boo-saltsjo-boo-6.jpg"],
  },
  {
    slug: "sundbyberg-sundbyberg",
    title: "Sundbyberg",
    ort: "Sundbyberg",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Sundbyberg i Sundbyberg. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Sundbyberg"],
    image: "/images/projekt/sundbyberg-sundbyberg.jpg",
    images: ["/images/projekt/sundbyberg-sundbyberg.jpg", "/images/projekt/sundbyberg-sundbyberg-2.jpg", "/images/projekt/sundbyberg-sundbyberg-3.jpg", "/images/projekt/sundbyberg-sundbyberg-4.jpg", "/images/projekt/sundbyberg-sundbyberg-5.jpg", "/images/projekt/sundbyberg-sundbyberg-6.jpg"],
  },
  {
    slug: "skokloster-skokloster",
    title: "Skokloster",
    ort: "Håbo",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Skokloster i Skokloster. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Håbo"],
    image: "/images/projekt/skokloster-skokloster.jpg",
    images: ["/images/projekt/skokloster-skokloster.jpg", "/images/projekt/skokloster-skokloster-2.jpg"],
  },
  {
    slug: "hasselby-hasselby",
    title: "Hässelby",
    ort: "Stockholm",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Hässelby i Hässelby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2022,
    taggar: ["Plåttak", "Stockholm"],
    image: "/images/projekt/hasselby-hasselby.jpg",
    images: ["/images/projekt/hasselby-hasselby.jpg", "/images/projekt/hasselby-hasselby-2.jpg", "/images/projekt/hasselby-hasselby-3.jpg", "/images/projekt/hasselby-hasselby-4.jpg", "/images/projekt/hasselby-hasselby-5.jpg", "/images/projekt/hasselby-hasselby-6.jpg"],
  },
  {
    slug: "norsborg-norsborg",
    title: "Norsborg",
    ort: "Botkyrka",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Norsborg i Norsborg. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2022,
    taggar: ["Betongtak", "Botkyrka"],
    image: "/images/projekt/norsborg-norsborg.jpg",
    images: ["/images/projekt/norsborg-norsborg.jpg", "/images/projekt/norsborg-norsborg-2.jpg", "/images/projekt/norsborg-norsborg-3.jpg"],
  },
  {
    slug: "vallingby-vallingby",
    title: "Vällingby",
    ort: "Stockholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Vällingby i Vällingby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/vallingby-vallingby.jpg",
    images: ["/images/projekt/vallingby-vallingby.jpg", "/images/projekt/vallingby-vallingby-2.jpg", "/images/projekt/vallingby-vallingby-3.jpg", "/images/projekt/vallingby-vallingby-4.jpg"],
  },
  {
    slug: "radhusslingan-strangnas",
    title: "Radhusslingan — Strängnäs",
    ort: "Strängnäs",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Radhusslingan i Strängnäs. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2021,
    taggar: ["Betongtak", "Strängnäs"],
    image: "/images/projekt/radhusslingan-strangnas.jpg",
    images: ["/images/projekt/radhusslingan-strangnas.jpg"],
  },
  {
    slug: "uttran-uttran",
    title: "Uttran",
    ort: "Uttran",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Uttran i Uttran. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2021,
    taggar: ["Tegeltak", "Uttran"],
    image: "/images/projekt/uttran-uttran.jpg",
    images: ["/images/projekt/uttran-uttran.jpg", "/images/projekt/uttran-uttran-2.jpg"],
  },
  {
    slug: "enkoping-enkoping",
    title: "Enköping",
    ort: "Enköping",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Enköping i Enköping. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2021,
    taggar: ["Plåttak", "Enköping"],
    image: "/images/projekt/enkoping-enkoping.jpg",
    images: ["/images/projekt/enkoping-enkoping.jpg", "/images/projekt/enkoping-enkoping-2.jpg", "/images/projekt/enkoping-enkoping-3.jpg", "/images/projekt/enkoping-enkoping-4.jpg", "/images/projekt/enkoping-enkoping-5.jpg", "/images/projekt/enkoping-enkoping-6.jpg", "/images/projekt/enkoping-enkoping-7.jpg", "/images/projekt/enkoping-enkoping-8.jpg", "/images/projekt/enkoping-enkoping-9.jpg"],
  },
  {
    slug: "upplands-bro-upplands-bro",
    title: "Upplands Bro",
    ort: "Upplands-Bro",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Upplands Bro i Upplands Bro. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2020,
    taggar: ["Betongtak", "Upplands-Bro"],
    image: "/images/projekt/upplands-bro-upplands-bro.jpg",
    images: ["/images/projekt/upplands-bro-upplands-bro.jpg", "/images/projekt/upplands-bro-upplands-bro-2.jpg", "/images/projekt/upplands-bro-upplands-bro-3.jpg", "/images/projekt/upplands-bro-upplands-bro-4.jpg", "/images/projekt/upplands-bro-upplands-bro-5.jpg", "/images/projekt/upplands-bro-upplands-bro-6.jpg"],
  },
  {
    slug: "gnesta-gnesta",
    title: "Gnesta",
    ort: "Gnesta",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Gnesta i Gnesta. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2020,
    taggar: ["Tegeltak", "Gnesta"],
    image: "/images/projekt/gnesta-gnesta.jpg",
    images: ["/images/projekt/gnesta-gnesta.jpg", "/images/projekt/gnesta-gnesta-2.jpg"],
  },
  {
    slug: "solna-solna",
    title: "Solna",
    ort: "Solna",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Solna i Solna. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Solna"],
    image: "/images/projekt/solna-solna.jpg",
    images: ["/images/projekt/solna-solna.jpg", "/images/projekt/solna-solna-2.jpg", "/images/projekt/solna-solna-3.jpg", "/images/projekt/solna-solna-4.jpg", "/images/projekt/solna-solna-5.jpg", "/images/projekt/solna-solna-6.jpg", "/images/projekt/solna-solna-7.jpg", "/images/projekt/solna-solna-8.jpg", "/images/projekt/solna-solna-9.jpg", "/images/projekt/solna-solna-10.jpg", "/images/projekt/solna-solna-11.jpg"],
  },
  {
    slug: "tumba-tumba",
    title: "Tumba",
    ort: "Botkyrka",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Tumba i Tumba. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2024,
    taggar: ["Tegeltak", "Botkyrka"],
    image: "/images/projekt/tumba-tumba.jpg",
    images: ["/images/projekt/tumba-tumba.jpg", "/images/projekt/tumba-tumba-2.jpg", "/images/projekt/tumba-tumba-3.jpg", "/images/projekt/tumba-tumba-4.jpg", "/images/projekt/tumba-tumba-5.jpg", "/images/projekt/tumba-tumba-6.jpg", "/images/projekt/tumba-tumba-7.jpg", "/images/projekt/tumba-tumba-8.jpg", "/images/projekt/tumba-tumba-9.jpg", "/images/projekt/tumba-tumba-10.jpg"],
  },
  {
    slug: "osteraker-osteraker",
    title: "Österåker",
    ort: "Österåker",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Österåker i Österåker. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2024,
    taggar: ["Plåttak", "Österåker"],
    image: "/images/projekt/osteraker-osteraker.jpg",
    images: ["/images/projekt/osteraker-osteraker.jpg", "/images/projekt/osteraker-osteraker-2.jpg", "/images/projekt/osteraker-osteraker-3.jpg", "/images/projekt/osteraker-osteraker-4.jpg", "/images/projekt/osteraker-osteraker-5.jpg", "/images/projekt/osteraker-osteraker-6.jpg", "/images/projekt/osteraker-osteraker-7.jpg", "/images/projekt/osteraker-osteraker-8.jpg", "/images/projekt/osteraker-osteraker-9.jpg", "/images/projekt/osteraker-osteraker-10.jpg", "/images/projekt/osteraker-osteraker-11.jpg"],
  },
  {
    slug: "frotunagrand-upplands-vasby",
    title: "Frötunagränd — Upplands Väsby",
    ort: "Upplands Väsby",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Frötunagränd i Upplands Väsby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Upplands Väsby"],
    image: "/images/projekt/frotunagrand-upplands-vasby.jpg",
    images: ["/images/projekt/frotunagrand-upplands-vasby.jpg", "/images/projekt/frotunagrand-upplands-vasby-2.jpg", "/images/projekt/frotunagrand-upplands-vasby-3.jpg", "/images/projekt/frotunagrand-upplands-vasby-4.jpg", "/images/projekt/frotunagrand-upplands-vasby-5.jpg", "/images/projekt/frotunagrand-upplands-vasby-6.jpg"],
  },
  {
    slug: "stenvagen-vaxholm",
    title: "Stenvägen — Vaxholm",
    ort: "Vaxholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Stenvägen i Vaxholm. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Vaxholm"],
    image: "/images/projekt/stenvagen-vaxholm.jpg",
    images: ["/images/projekt/stenvagen-vaxholm.jpg", "/images/projekt/stenvagen-vaxholm-2.jpg", "/images/projekt/stenvagen-vaxholm-3.jpg", "/images/projekt/stenvagen-vaxholm-4.jpg", "/images/projekt/stenvagen-vaxholm-5.jpg"],
  },
  {
    slug: "skovelvagen-alvsjo-2",
    title: "Skovelvägen — Älvsjö",
    ort: "Stockholm",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Skovelvägen i Älvsjö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Stockholm"],
    image: "/images/projekt/skovelvagen-alvsjo-2.jpg",
    images: ["/images/projekt/skovelvagen-alvsjo-2.jpg", "/images/projekt/skovelvagen-alvsjo-2-2.jpg", "/images/projekt/skovelvagen-alvsjo-2-3.jpg", "/images/projekt/skovelvagen-alvsjo-2-4.jpg"],
  },
  {
    slug: "enskededalen-stockholm",
    title: "Enskededalen — Stockholm",
    ort: "Stockholm",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Enskededalen i Stockholm. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/enskededalen-stockholm.jpg",
    images: ["/images/projekt/enskededalen-stockholm.jpg", "/images/projekt/enskededalen-stockholm-2.jpg", "/images/projekt/enskededalen-stockholm-3.jpg", "/images/projekt/enskededalen-stockholm-4.jpg", "/images/projekt/enskededalen-stockholm-5.jpg", "/images/projekt/enskededalen-stockholm-6.jpg", "/images/projekt/enskededalen-stockholm-7.jpg", "/images/projekt/enskededalen-stockholm-8.jpg", "/images/projekt/enskededalen-stockholm-9.jpg", "/images/projekt/enskededalen-stockholm-10.jpg", "/images/projekt/enskededalen-stockholm-11.jpg", "/images/projekt/enskededalen-stockholm-12.jpg"],
  },
  {
    slug: "haggvagen-jarfalla",
    title: "Häggvägen — Järfälla",
    ort: "Järfälla",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Häggvägen i Järfälla. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2022,
    taggar: ["Plåttak", "Järfälla"],
    image: "/images/projekt/haggvagen-jarfalla.jpg",
    images: ["/images/projekt/haggvagen-jarfalla.jpg", "/images/projekt/haggvagen-jarfalla-2.jpg", "/images/projekt/haggvagen-jarfalla-3.jpg", "/images/projekt/haggvagen-jarfalla-4.jpg", "/images/projekt/haggvagen-jarfalla-5.jpg", "/images/projekt/haggvagen-jarfalla-6.jpg", "/images/projekt/haggvagen-jarfalla-7.jpg", "/images/projekt/haggvagen-jarfalla-8.jpg", "/images/projekt/haggvagen-jarfalla-9.jpg", "/images/projekt/haggvagen-jarfalla-10.jpg"],
  },
];

export function getProjekt(slug: string): Projekt | undefined {
  return projekt.find((p) => p.slug === slug);
}

export function getProjektByOrt(ort: string): Projekt[] {
  return projekt.filter((p) => p.ort === ort);
}
