export type Projekt = {
  slug: string;
  title: string;
  ort: string;
  kvm: number;
  typ: string;
  beskrivning: string;
  material: string;
  år: number;
  taggar: string[];
  image: string;
  images: string[];
  imageBefore?: string;
};

export const projekt: Projekt[] = [
  {
    slug: "fagerasen-vrena",
    title: "Fageråsen — Vrena",
    ort: "Nyköping",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Fageråsen i Vrena. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Nyköping"],
    image: "/images/projekt/fagerasen-vrena.jpg",
    images: ["/images/projekt/fagerasen-vrena.jpg", "/images/projekt/fagerasen-vrena-2.jpg", "/images/projekt/fagerasen-vrena-3.jpg"],
  },
  {
    slug: "plommonvagen-bromma",
    title: "Plommonvägen — Bromma",
    ort: "Stockholm",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Plommonvägen i Bromma. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2024,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/plommonvagen-bromma.jpg",
    images: ["/images/projekt/plommonvagen-bromma.jpg", "/images/projekt/plommonvagen-bromma-2.jpg", "/images/projekt/plommonvagen-bromma-3.jpg", "/images/projekt/plommonvagen-bromma-4.jpg", "/images/projekt/plommonvagen-bromma-5.jpg", "/images/projekt/plommonvagen-bromma-6.jpg", "/images/projekt/plommonvagen-bromma-7.jpg", "/images/projekt/plommonvagen-bromma-8.jpg", "/images/projekt/plommonvagen-bromma-9.jpg", "/images/projekt/plommonvagen-bromma-10.jpg"],
  },
  {
    slug: "hakevagen-djursholm",
    title: "Hakevägen — Djursholm",
    ort: "Danderyd",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Hakevägen i Djursholm. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Danderyd"],
    image: "/images/projekt/hakevagen-djursholm.jpg",
    images: ["/images/projekt/hakevagen-djursholm.jpg", "/images/projekt/hakevagen-djursholm-2.jpg", "/images/projekt/hakevagen-djursholm-3.jpg", "/images/projekt/hakevagen-djursholm-4.jpg", "/images/projekt/hakevagen-djursholm-5.jpg", "/images/projekt/hakevagen-djursholm-6.jpg", "/images/projekt/hakevagen-djursholm-7.jpg", "/images/projekt/hakevagen-djursholm-8.jpg", "/images/projekt/hakevagen-djursholm-9.jpg", "/images/projekt/hakevagen-djursholm-10.jpg", "/images/projekt/hakevagen-djursholm-11.jpg", "/images/projekt/hakevagen-djursholm-12.jpg"],
  },
  {
    slug: "timmerbacken-tumba",
    title: "Timmerbacken — Tumba",
    ort: "Botkyrka",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Timmerbacken i Tumba. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Botkyrka"],
    image: "/images/projekt/timmerbacken-tumba.jpg",
    images: ["/images/projekt/timmerbacken-tumba.jpg", "/images/projekt/timmerbacken-tumba-2.jpg", "/images/projekt/timmerbacken-tumba-3.jpg", "/images/projekt/timmerbacken-tumba-4.jpg", "/images/projekt/timmerbacken-tumba-5.jpg", "/images/projekt/timmerbacken-tumba-6.jpg", "/images/projekt/timmerbacken-tumba-7.jpg", "/images/projekt/timmerbacken-tumba-8.jpg", "/images/projekt/timmerbacken-tumba-9.jpg", "/images/projekt/timmerbacken-tumba-10.jpg", "/images/projekt/timmerbacken-tumba-11.jpg", "/images/projekt/timmerbacken-tumba-12.jpg"],
  },
  {
    slug: "skovelvagen-alvsjo",
    title: "Skovelvägen — Älvsjö",
    ort: "Stockholm",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Skovelvägen i Älvsjö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2023,
    taggar: ["Plåttak", "Stockholm"],
    image: "/images/projekt/skovelvagen-alvsjo.jpg",
    images: ["/images/projekt/skovelvagen-alvsjo.jpg", "/images/projekt/skovelvagen-alvsjo-2.jpg", "/images/projekt/skovelvagen-alvsjo-3.jpg", "/images/projekt/skovelvagen-alvsjo-4.jpg"],
  },
  {
    slug: "solfagravagen-huddinge",
    title: "Solfagravägen — Huddinge",
    ort: "Huddinge",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Solfagravägen i Huddinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Huddinge"],
    image: "/images/projekt/solfagravagen-huddinge.jpg",
    images: ["/images/projekt/solfagravagen-huddinge.jpg", "/images/projekt/solfagravagen-huddinge-2.jpg", "/images/projekt/solfagravagen-huddinge-3.jpg", "/images/projekt/solfagravagen-huddinge-4.jpg", "/images/projekt/solfagravagen-huddinge-5.jpg", "/images/projekt/solfagravagen-huddinge-6.jpg"],
  },
  {
    slug: "sorgardsvagen-bromma",
    title: "Sörgårdsvägen — Bromma",
    ort: "Stockholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Sörgårdsvägen i Bromma. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/sorgardsvagen-bromma.jpg",
    images: ["/images/projekt/sorgardsvagen-bromma.jpg", "/images/projekt/sorgardsvagen-bromma-2.jpg", "/images/projekt/sorgardsvagen-bromma-3.jpg", "/images/projekt/sorgardsvagen-bromma-4.jpg", "/images/projekt/sorgardsvagen-bromma-5.jpg", "/images/projekt/sorgardsvagen-bromma-6.jpg"],
  },
  {
    slug: "kastanjetunet-lidingo",
    title: "Kastanjetunet — Lidingö",
    ort: "Lidingö",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Kastanjetunet i Lidingö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2022,
    taggar: ["Betongtak", "Lidingö"],
    image: "/images/projekt/kastanjetunet-lidingo.jpg",
    images: ["/images/projekt/kastanjetunet-lidingo.jpg", "/images/projekt/kastanjetunet-lidingo-2.jpg", "/images/projekt/kastanjetunet-lidingo-3.jpg", "/images/projekt/kastanjetunet-lidingo-4.jpg", "/images/projekt/kastanjetunet-lidingo-5.jpg", "/images/projekt/kastanjetunet-lidingo-6.jpg", "/images/projekt/kastanjetunet-lidingo-7.jpg", "/images/projekt/kastanjetunet-lidingo-8.jpg", "/images/projekt/kastanjetunet-lidingo-9.jpg", "/images/projekt/kastanjetunet-lidingo-10.jpg", "/images/projekt/kastanjetunet-lidingo-11.jpg", "/images/projekt/kastanjetunet-lidingo-12.jpg"],
  },
  {
    slug: "prastgardsvagen-tumba",
    title: "Prästgårdsvägen — Tumba",
    ort: "Botkyrka",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Prästgårdsvägen i Tumba. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Botkyrka"],
    image: "/images/projekt/prastgardsvagen-tumba.jpg",
    images: ["/images/projekt/prastgardsvagen-tumba.jpg", "/images/projekt/prastgardsvagen-tumba-2.jpg", "/images/projekt/prastgardsvagen-tumba-3.jpg", "/images/projekt/prastgardsvagen-tumba-4.jpg"],
  },
  {
    slug: "skacklingevagen-tumba",
    title: "Skäcklingevägen — Tumba",
    ort: "Botkyrka",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Skäcklingevägen i Tumba. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2021,
    taggar: ["Plåttak", "Botkyrka"],
    image: "/images/projekt/skacklingevagen-tumba.jpg",
    images: ["/images/projekt/skacklingevagen-tumba.jpg"],
  },
  {
    slug: "skrattmasvagen-farsta",
    title: "Skrattmåsvägen — Farsta",
    ort: "Stockholm",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Skrattmåsvägen i Farsta. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2021,
    taggar: ["Betongtak", "Stockholm"],
    image: "/images/projekt/skrattmasvagen-farsta.jpg",
    images: ["/images/projekt/skrattmasvagen-farsta.jpg", "/images/projekt/skrattmasvagen-farsta-2.jpg", "/images/projekt/skrattmasvagen-farsta-3.jpg", "/images/projekt/skrattmasvagen-farsta-4.jpg"],
  },
  {
    slug: "vartavagen-taby",
    title: "Värtavägen — Täby",
    ort: "Täby",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Värtavägen i Täby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2021,
    taggar: ["Tegeltak", "Täby"],
    image: "/images/projekt/vartavagen-taby.jpg",
    images: ["/images/projekt/vartavagen-taby.jpg"],
  },
  {
    slug: "nytorpsvagen-koping",
    title: "Nytorpsvägen — Köping",
    ort: "Köping",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Nytorpsvägen i Köping. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2020,
    taggar: ["Betongtak", "Köping"],
    image: "/images/projekt/nytorpsvagen-koping.jpg",
    images: ["/images/projekt/nytorpsvagen-koping.jpg", "/images/projekt/nytorpsvagen-koping-2.jpg", "/images/projekt/nytorpsvagen-koping-3.jpg", "/images/projekt/nytorpsvagen-koping-4.jpg", "/images/projekt/nytorpsvagen-koping-5.jpg", "/images/projekt/nytorpsvagen-koping-6.jpg"],
  },
  {
    slug: "norrangsvagen-huddinge",
    title: "Norrängsvägen — Huddinge",
    ort: "Huddinge",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Norrängsvägen i Huddinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2020,
    taggar: ["Tegeltak", "Huddinge"],
    image: "/images/projekt/norrangsvagen-huddinge.jpg",
    images: ["/images/projekt/norrangsvagen-huddinge.jpg", "/images/projekt/norrangsvagen-huddinge-2.jpg", "/images/projekt/norrangsvagen-huddinge-3.jpg", "/images/projekt/norrangsvagen-huddinge-4.jpg"],
  },
  {
    slug: "alstromervagen-skarholmen",
    title: "Alströmervägen — Skärholmen",
    ort: "Stockholm",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Alströmervägen i Skärholmen. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2024,
    taggar: ["Plåttak", "Stockholm"],
    image: "/images/projekt/alstromervagen-skarholmen.jpg",
    images: ["/images/projekt/alstromervagen-skarholmen.jpg", "/images/projekt/alstromervagen-skarholmen-2.jpg", "/images/projekt/alstromervagen-skarholmen-3.jpg", "/images/projekt/alstromervagen-skarholmen-4.jpg"],
  },
  {
    slug: "takrenovering-taby",
    title: "Takrenovering — Täby",
    ort: "Täby",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takrenovering i Täby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2024,
    taggar: ["Betongtak", "Täby"],
    image: "/images/projekt/takrenovering-taby.jpg",
    images: ["/images/projekt/takrenovering-taby.jpg", "/images/projekt/takrenovering-taby-2.jpg", "/images/projekt/takrenovering-taby-3.jpg", "/images/projekt/takrenovering-taby-4.jpg", "/images/projekt/takrenovering-taby-5.jpg", "/images/projekt/takrenovering-taby-6.jpg", "/images/projekt/takrenovering-taby-7.jpg", "/images/projekt/takrenovering-taby-8.jpg", "/images/projekt/takrenovering-taby-9.jpg", "/images/projekt/takrenovering-taby-10.jpg", "/images/projekt/takrenovering-taby-11.jpg", "/images/projekt/takrenovering-taby-12.jpg", "/images/projekt/takrenovering-taby-13.jpg"],
  },
  {
    slug: "takrenovering-sollentuna",
    title: "Takrenovering — Sollentuna",
    ort: "Sollentuna",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takrenovering i Sollentuna. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2024,
    taggar: ["Tegeltak", "Sollentuna"],
    image: "/images/projekt/takrenovering-sollentuna.jpg",
    images: ["/images/projekt/takrenovering-sollentuna.jpg", "/images/projekt/takrenovering-sollentuna-2.jpg", "/images/projekt/takrenovering-sollentuna-3.jpg", "/images/projekt/takrenovering-sollentuna-4.jpg"],
  },
  {
    slug: "takomlaggning-huddinge",
    title: "Takomläggning — Huddinge",
    ort: "Huddinge",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning i Huddinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Huddinge"],
    image: "/images/projekt/takomlaggning-huddinge.jpg",
    images: ["/images/projekt/takomlaggning-huddinge.jpg", "/images/projekt/takomlaggning-huddinge-2.jpg", "/images/projekt/takomlaggning-huddinge-3.jpg", "/images/projekt/takomlaggning-huddinge-4.jpg", "/images/projekt/takomlaggning-huddinge-5.jpg", "/images/projekt/takomlaggning-huddinge-6.jpg", "/images/projekt/takomlaggning-huddinge-7.jpg", "/images/projekt/takomlaggning-huddinge-8.jpg", "/images/projekt/takomlaggning-huddinge-9.jpg"],
  },
  {
    slug: "takomlaggning-upplands-vasby",
    title: "Takomläggning — Upplands Väsby",
    ort: "Upplands Väsby",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning i Upplands Väsby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2023,
    taggar: ["Plåttak", "Upplands Väsby"],
    image: "/images/projekt/takomlaggning-upplands-vasby.jpg",
    images: ["/images/projekt/takomlaggning-upplands-vasby.jpg", "/images/projekt/takomlaggning-upplands-vasby-2.jpg", "/images/projekt/takomlaggning-upplands-vasby-3.jpg", "/images/projekt/takomlaggning-upplands-vasby-4.jpg", "/images/projekt/takomlaggning-upplands-vasby-5.jpg", "/images/projekt/takomlaggning-upplands-vasby-6.jpg", "/images/projekt/takomlaggning-upplands-vasby-7.jpg", "/images/projekt/takomlaggning-upplands-vasby-8.jpg", "/images/projekt/takomlaggning-upplands-vasby-9.jpg", "/images/projekt/takomlaggning-upplands-vasby-10.jpg", "/images/projekt/takomlaggning-upplands-vasby-11.jpg", "/images/projekt/takomlaggning-upplands-vasby-12.jpg", "/images/projekt/takomlaggning-upplands-vasby-13.jpg", "/images/projekt/takomlaggning-upplands-vasby-14.jpg", "/images/projekt/takomlaggning-upplands-vasby-15.jpg", "/images/projekt/takomlaggning-upplands-vasby-16.jpg", "/images/projekt/takomlaggning-upplands-vasby-17.jpg", "/images/projekt/takomlaggning-upplands-vasby-18.jpg", "/images/projekt/takomlaggning-upplands-vasby-19.jpg", "/images/projekt/takomlaggning-upplands-vasby-20.jpg", "/images/projekt/takomlaggning-upplands-vasby-21.jpg", "/images/projekt/takomlaggning-upplands-vasby-22.jpg", "/images/projekt/takomlaggning-upplands-vasby-23.jpg", "/images/projekt/takomlaggning-upplands-vasby-24.jpg", "/images/projekt/takomlaggning-upplands-vasby-25.jpg", "/images/projekt/takomlaggning-upplands-vasby-26.jpg", "/images/projekt/takomlaggning-upplands-vasby-27.jpg"],
  },
  {
    slug: "takomlaggning-lidingo",
    title: "Takomläggning — Lidingö",
    ort: "Lidingö",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning i Lidingö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Lidingö"],
    image: "/images/projekt/takomlaggning-lidingo.jpg",
    images: ["/images/projekt/takomlaggning-lidingo.jpg", "/images/projekt/takomlaggning-lidingo-2.jpg", "/images/projekt/takomlaggning-lidingo-3.jpg", "/images/projekt/takomlaggning-lidingo-4.jpg"],
  },
  {
    slug: "takomlaggning-enskede",
    title: "Takomläggning — Enskede",
    ort: "Stockholm",
    kvm: 160,
    typ: "Betongtak",
    beskrivning: "Takomläggning i Enskede. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2022,
    taggar: ["Betongtak", "Stockholm"],
    image: "/images/projekt/takomlaggning-enskede.jpg",
    images: ["/images/projekt/takomlaggning-enskede.jpg", "/images/projekt/takomlaggning-enskede-2.jpg", "/images/projekt/takomlaggning-enskede-3.jpg", "/images/projekt/takomlaggning-enskede-4.jpg", "/images/projekt/takomlaggning-enskede-5.jpg", "/images/projekt/takomlaggning-enskede-6.jpg", "/images/projekt/takomlaggning-enskede-7.jpg", "/images/projekt/takomlaggning-enskede-8.jpg"],
  },
  {
    slug: "totalrenovering-jarfalla",
    title: "Totalrenovering radhus — Järfälla",
    ort: "Järfälla",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Totalrenovering radhus i Järfälla. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2021,
    taggar: ["Betongtak", "Järfälla"],
    image: "/images/projekt/totalrenovering-jarfalla.jpg",
    images: ["/images/projekt/totalrenovering-jarfalla.jpg", "/images/projekt/totalrenovering-jarfalla-2.jpg", "/images/projekt/totalrenovering-jarfalla-3.jpg", "/images/projekt/totalrenovering-jarfalla-4.jpg", "/images/projekt/totalrenovering-jarfalla-5.jpg", "/images/projekt/totalrenovering-jarfalla-6.jpg", "/images/projekt/totalrenovering-jarfalla-7.jpg", "/images/projekt/totalrenovering-jarfalla-8.jpg", "/images/projekt/totalrenovering-jarfalla-9.jpg", "/images/projekt/totalrenovering-jarfalla-10.jpg", "/images/projekt/totalrenovering-jarfalla-11.jpg", "/images/projekt/totalrenovering-jarfalla-12.jpg"],
  },
  {
    slug: "lagenhetsrenovering-kungsholmen",
    title: "Lägenhetsrenovering — Kungsholmen",
    ort: "Stockholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Lägenhetsrenovering i Kungsholmen. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2020,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/lagenhetsrenovering-kungsholmen.jpg",
    images: ["/images/projekt/lagenhetsrenovering-kungsholmen.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-2.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-3.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-4.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-5.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-6.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-7.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-8.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-9.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-10.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-11.jpg", "/images/projekt/lagenhetsrenovering-kungsholmen-12.jpg"],
  },
  {
    slug: "takomlaggning-nykoping",
    title: "Takomläggning K-märkt — Nyköping",
    ort: "Nyköping",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning K-märkt i Nyköping. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2020,
    taggar: ["Betongtak", "Nyköping"],
    image: "/images/projekt/takomlaggning-nykoping.jpg",
    images: ["/images/projekt/takomlaggning-nykoping.jpg", "/images/projekt/takomlaggning-nykoping-2.jpg", "/images/projekt/takomlaggning-nykoping-3.jpg"],
  },
  {
    slug: "takomlaggning-farsta",
    title: "Takomläggning — Farsta",
    ort: "Stockholm",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning i Farsta. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2024,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/takomlaggning-farsta.jpg",
    images: ["/images/projekt/takomlaggning-farsta.jpg", "/images/projekt/takomlaggning-farsta-2.jpg", "/images/projekt/takomlaggning-farsta-3.jpg"],
  },
  {
    slug: "takomlaggning-grodinge",
    title: "Takomläggning — Grödinge",
    ort: "Botkyrka",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning i Grödinge. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2024,
    taggar: ["Plåttak", "Botkyrka"],
    image: "/images/projekt/takomlaggning-grodinge.jpg",
    images: ["/images/projekt/takomlaggning-grodinge.jpg", "/images/projekt/takomlaggning-grodinge-2.jpg", "/images/projekt/takomlaggning-grodinge-3.jpg"],
  },
  {
    slug: "takomlaggning-skokloster",
    title: "Takomläggning — Skokloster",
    ort: "Håbo",
    kvm: 170,
    typ: "Tegeltak",
    beskrivning: "Takomläggning i Skokloster. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Håbo"],
    image: "/images/projekt/takomlaggning-skokloster.jpg",
    images: ["/images/projekt/takomlaggning-skokloster.jpg", "/images/projekt/takomlaggning-skokloster-2.jpg"],
  },
  {
    slug: "takomlaggning-hasselby",
    title: "Takomläggning — Hässelby",
    ort: "Stockholm",
    kvm: 145,
    typ: "Plåttak",
    beskrivning: "Takomläggning i Hässelby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2022,
    taggar: ["Plåttak", "Stockholm"],
    image: "/images/projekt/takomlaggning-hasselby.jpg",
    images: ["/images/projekt/takomlaggning-hasselby.jpg", "/images/projekt/takomlaggning-hasselby-2.jpg", "/images/projekt/takomlaggning-hasselby-3.jpg", "/images/projekt/takomlaggning-hasselby-4.jpg", "/images/projekt/takomlaggning-hasselby-5.jpg", "/images/projekt/takomlaggning-hasselby-6.jpg"],
  },
  {
    slug: "badrumsrenovering-norsborg",
    title: "Badrumsrenovering — Norsborg",
    ort: "Botkyrka",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Badrumsrenovering i Norsborg. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2022,
    taggar: ["Betongtak", "Botkyrka"],
    image: "/images/projekt/badrumsrenovering-norsborg.jpg",
    images: ["/images/projekt/badrumsrenovering-norsborg.jpg", "/images/projekt/badrumsrenovering-norsborg-2.jpg", "/images/projekt/badrumsrenovering-norsborg-3.jpg"],
  },
  {
    slug: "fasadmalning-vallingby",
    title: "Fasadmålning — Vällingby",
    ort: "Stockholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Fasadmålning i Vällingby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/fasadmalning-vallingby.jpg",
    images: ["/images/projekt/fasadmalning-vallingby.jpg", "/images/projekt/fasadmalning-vallingby-2.jpg", "/images/projekt/fasadmalning-vallingby-3.jpg", "/images/projekt/fasadmalning-vallingby-4.jpg"],
  },
  {
    slug: "radhusslingan-strangnas",
    title: "Radhusslingan — Strängnäs",
    ort: "Strängnäs",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Radhusslingan i Strängnäs. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2021,
    taggar: ["Betongtak", "Strängnäs"],
    image: "/images/projekt/radhusslingan-strangnas.jpg",
    images: ["/images/projekt/radhusslingan-strangnas.jpg"],
  },
  {
    slug: "nybyggnation-uttran",
    title: "Nybyggnation entrébyggnad — Uttran",
    ort: "Botkyrka",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Nybyggnation entrébyggnad i Uttran. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2021,
    taggar: ["Tegeltak", "Uttran"],
    image: "/images/projekt/nybyggnation-uttran.jpg",
    images: ["/images/projekt/nybyggnation-uttran.jpg", "/images/projekt/nybyggnation-uttran-2.jpg"],
  },
  {
    slug: "finplanering-enkoping",
    title: "Finplanering — Bredsand, Enköping",
    ort: "Enköping",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Finplanering i Bredsand, Enköping. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2021,
    taggar: ["Plåttak", "Enköping"],
    image: "/images/projekt/finplanering-enkoping.jpg",
    images: ["/images/projekt/finplanering-enkoping.jpg", "/images/projekt/finplanering-enkoping-2.jpg", "/images/projekt/finplanering-enkoping-3.jpg", "/images/projekt/finplanering-enkoping-4.jpg", "/images/projekt/finplanering-enkoping-5.jpg", "/images/projekt/finplanering-enkoping-6.jpg", "/images/projekt/finplanering-enkoping-7.jpg", "/images/projekt/finplanering-enkoping-8.jpg", "/images/projekt/finplanering-enkoping-9.jpg"],
  },
  {
    slug: "takomlaggning-upplands-bro",
    title: "Takomläggning plåttak — Upplands Bro",
    ort: "Upplands-Bro",
    kvm: 140,
    typ: "Betongtak",
    beskrivning: "Takomläggning plåttak i Upplands Bro. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2020,
    taggar: ["Betongtak", "Upplands-Bro"],
    image: "/images/projekt/takomlaggning-upplands-bro.jpg",
    images: ["/images/projekt/takomlaggning-upplands-bro.jpg", "/images/projekt/takomlaggning-upplands-bro-2.jpg", "/images/projekt/takomlaggning-upplands-bro-3.jpg", "/images/projekt/takomlaggning-upplands-bro-4.jpg", "/images/projekt/takomlaggning-upplands-bro-5.jpg", "/images/projekt/takomlaggning-upplands-bro-6.jpg"],
  },
  {
    slug: "takomlaggning-gnesta",
    title: "Takomläggning — Gnesta",
    ort: "Gnesta",
    kvm: 150,
    typ: "Tegeltak",
    beskrivning: "Takomläggning i Gnesta. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2020,
    taggar: ["Tegeltak", "Gnesta"],
    image: "/images/projekt/takomlaggning-gnesta.jpg",
    images: ["/images/projekt/takomlaggning-gnesta.jpg", "/images/projekt/takomlaggning-gnesta-2.jpg"],
  },
  {
    slug: "frotunagrand-upplands-vasby",
    title: "Frötunagränd — Upplands Väsby",
    ort: "Upplands Väsby",
    kvm: 155,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Frötunagränd i Upplands Väsby. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Upplands Väsby"],
    image: "/images/projekt/frotunagrand-upplands-vasby.jpg",
    images: ["/images/projekt/frotunagrand-upplands-vasby.jpg", "/images/projekt/frotunagrand-upplands-vasby-2.jpg", "/images/projekt/frotunagrand-upplands-vasby-3.jpg", "/images/projekt/frotunagrand-upplands-vasby-4.jpg", "/images/projekt/frotunagrand-upplands-vasby-5.jpg", "/images/projekt/frotunagrand-upplands-vasby-6.jpg"],
  },
  {
    slug: "stenvagen-vaxholm",
    title: "Stenvägen — Vaxholm",
    ort: "Vaxholm",
    kvm: 135,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Stenvägen i Vaxholm. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2023,
    taggar: ["Tegeltak", "Vaxholm"],
    image: "/images/projekt/stenvagen-vaxholm.jpg",
    images: ["/images/projekt/stenvagen-vaxholm.jpg", "/images/projekt/stenvagen-vaxholm-2.jpg", "/images/projekt/stenvagen-vaxholm-3.jpg", "/images/projekt/stenvagen-vaxholm-4.jpg", "/images/projekt/stenvagen-vaxholm-5.jpg"],
  },
  {
    slug: "skovelvagen-alvsjo-2",
    title: "Skovelvägen — Älvsjö",
    ort: "Stockholm",
    kvm: 165,
    typ: "Betongtak",
    beskrivning: "Takomläggning med betongtak på Skovelvägen i Älvsjö. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier betongtakpannor",
    år: 2023,
    taggar: ["Betongtak", "Stockholm"],
    image: "/images/projekt/skovelvagen-alvsjo-2.jpg",
    images: ["/images/projekt/skovelvagen-alvsjo-2.jpg", "/images/projekt/skovelvagen-alvsjo-2-2.jpg", "/images/projekt/skovelvagen-alvsjo-2-3.jpg", "/images/projekt/skovelvagen-alvsjo-2-4.jpg"],
  },
  {
    slug: "enskededalen-stockholm",
    title: "Enskededalen — Stockholm",
    ort: "Stockholm",
    kvm: 130,
    typ: "Tegeltak",
    beskrivning: "Takomläggning med tegeltak på Enskededalen i Stockholm. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier tegeltakpannor",
    år: 2022,
    taggar: ["Tegeltak", "Stockholm"],
    image: "/images/projekt/enskededalen-stockholm.jpg",
    images: ["/images/projekt/enskededalen-stockholm.jpg", "/images/projekt/enskededalen-stockholm-2.jpg", "/images/projekt/enskededalen-stockholm-3.jpg", "/images/projekt/enskededalen-stockholm-4.jpg", "/images/projekt/enskededalen-stockholm-5.jpg", "/images/projekt/enskededalen-stockholm-6.jpg", "/images/projekt/enskededalen-stockholm-7.jpg", "/images/projekt/enskededalen-stockholm-8.jpg", "/images/projekt/enskededalen-stockholm-9.jpg", "/images/projekt/enskededalen-stockholm-10.jpg", "/images/projekt/enskededalen-stockholm-11.jpg", "/images/projekt/enskededalen-stockholm-12.jpg"],
  },
  {
    slug: "haggvagen-jarfalla",
    title: "Häggvägen — Järfälla",
    ort: "Järfälla",
    kvm: 175,
    typ: "Plåttak",
    beskrivning: "Takomläggning med plåttak på Häggvägen i Järfälla. Komplett totalentreprenad med fast pris och Monier-garanti.",
    material: "Monier plåttakpannor",
    år: 2022,
    taggar: ["Plåttak", "Järfälla"],
    image: "/images/projekt/haggvagen-jarfalla.jpg",
    images: ["/images/projekt/haggvagen-jarfalla.jpg", "/images/projekt/haggvagen-jarfalla-2.jpg", "/images/projekt/haggvagen-jarfalla-3.jpg", "/images/projekt/haggvagen-jarfalla-4.jpg", "/images/projekt/haggvagen-jarfalla-5.jpg", "/images/projekt/haggvagen-jarfalla-6.jpg", "/images/projekt/haggvagen-jarfalla-7.jpg", "/images/projekt/haggvagen-jarfalla-8.jpg", "/images/projekt/haggvagen-jarfalla-9.jpg", "/images/projekt/haggvagen-jarfalla-10.jpg"],
  }
];

export function getProjekt(slug: string): Projekt | undefined {
  return projekt.find((p) => p.slug === slug);
}

export function getProjektByOrt(ort: string): Projekt[] {
  return projekt.filter((p) => p.ort === ort);
}
