/**
 * Enda sanningskälla för kundomdömen. Renderas både i ReviewCarousel
 * (startsidan) och på /omdomen, så att samma kund alltid visas likadant.
 *
 * Detta är VERIFIERADE omdömen från externa marknadsplatser (BraByggare,
 * Offerta, Servicefinder), citerade ordagrant (långa omdömen är förkortade
 * till en representativ del). Lägg till nya omdömen här, inte i enskilda
 * komponenter. Sätt rätt `source`, `betyg` och `datumISO` per omdöme.
 *
 * Tak-omdömen ligger först eftersom de är mest relevanta för en takläggare.
 */

export type ReviewSource = "servicefinder" | "brabyggare" | "offerta";

export const SOURCE_LABEL: Record<ReviewSource, string> = {
  servicefinder: "Servicefinder",
  brabyggare: "BraByggare",
  offerta: "Offerta",
};

export interface Testimonial {
  name: string;
  ort?: string;
  /** Kort etikett för material/tjänst, t.ex. "Takbyte" */
  tjanst: string;
  /** Takyta i kvm, om angiven */
  kvm?: number;
  betyg: number;
  text: string;
  source: ReviewSource;
  /** Visningsdatum, t.ex. "16 augusti 2023" */
  datum: string;
  /** ISO-datum för structured data */
  datumISO: string;
}

export const testimonials: Testimonial[] = [
  {
    name: "KHOSRO SAFAEI",
    tjanst: "Takbyte",
    betyg: 5,
    text: "Mycket nöjd med arbetet. Väldigt proffsigt och rutinerat utförande. De lyssnar verkligen på kunden istället för att bara köra sitt eget race. Rekommenderas varmt. Tackar Simon.",
    source: "brabyggare",
    datum: "11 mars 2026",
    datumISO: "2026-03-11",
  },
  {
    name: "Pauli",
    ort: "Solna",
    tjanst: "Tegeltak",
    kvm: 150,
    betyg: 5,
    text: "Väldigt professionellt och effektivt genomförande, i utlovad tidtabell. Väldigt bra och detaljerad offert som också stämde exakt med slutfakturan. Rekommenderas varmt!",
    source: "offerta",
    datum: "23 februari 2026",
    datumISO: "2026-02-23",
  },
  {
    name: "Linda",
    tjanst: "Golv & trappa",
    betyg: 5,
    text: "Slipning och betsning av trappa och parkettgolv som var i mycket dåligt skick. Resultatet blev fantastiskt, ytorna ser i princip nya ut igen. Arbetet utfördes noggrant, effektivt och med stor yrkesskicklighet. Kan varmt rekommendera.",
    source: "brabyggare",
    datum: "29 december 2025",
    datumISO: "2025-12-29",
  },
  {
    name: "Leli",
    ort: "Upplands-Bro",
    tjanst: "Takläggning",
    kvm: 100,
    betyg: 5,
    text: "Bra jobb, smidigt och enkelt.",
    source: "offerta",
    datum: "11 december 2025",
    datumISO: "2025-12-11",
  },
  {
    name: "Dominic",
    ort: "Spånga",
    tjanst: "Takläggning",
    kvm: 150,
    betyg: 5,
    text: "Very happy with our roof replacement from Janne and the team. Good communication, impressive speed of construction and high quality installation. Would highly recommend.",
    source: "offerta",
    datum: "6 november 2025",
    datumISO: "2025-11-06",
  },
  {
    name: "Daniel Nilsson",
    tjanst: "Takbyte",
    betyg: 5,
    text: "Helt fantastiskt, snabbhet och kvalitet i toppklass! Teamet var extremt snabba utan att tumma på kvaliteten. Tydlig kommunikation hela vägen och jag blev kontinuerligt uppdaterad. Slutresultatet blev ett riktigt snyggt och välgjort tak som överträffade mina förväntningar.",
    source: "brabyggare",
    datum: "27 oktober 2025",
    datumISO: "2025-10-27",
  },
  {
    name: "Anders",
    ort: "Södertälje",
    tjanst: "Takläggning",
    kvm: 160,
    betyg: 5,
    text: "Sands AB var professionella och tillmötesgående. Arbetet utfördes raskt och med stor precision. Efter att arbetet var utfört städade de runt huset och lämnade inget efter sig. Kan definitivt rekommendera.",
    source: "offerta",
    datum: "26 oktober 2025",
    datumISO: "2025-10-26",
  },
  {
    name: "Henrik",
    ort: "Tyresö",
    tjanst: "Takläggning",
    kvm: 170,
    betyg: 5,
    text: "Riktigt bra att ha och göra med. Snabba, noggranna och gjort ett riktigt bra jobb som takbyte. Supernöjd och till ett bra pris dessutom. Kan starkt rekommendera.",
    source: "offerta",
    datum: "19 september 2025",
    datumISO: "2025-09-19",
  },
  {
    name: "Joakim",
    ort: "Hässelby",
    tjanst: "Takläggning",
    kvm: 70,
    betyg: 5,
    text: "Efter lite ändringar av startdatumet fungerade allt felfritt. Snabbt och bra utförande. Ett extra plus för bra städning på tomten efteråt. De sa att det skulle ta 3-4 dagar men det tog 2 dagar.",
    source: "offerta",
    datum: "3 juli 2025",
    datumISO: "2025-07-03",
  },
  {
    name: "Hassan Oubakkas",
    tjanst: "Takbyte",
    betyg: 5,
    text: "Bästa tänkbara upplevelse! Hela processen präglades av utmärkt kommunikation, hög professionalism och engagemang för kvalitet. Simon, som lämnade offerten, förklarade allt tydligt och tog sig tid att svara på alla mina frågor. Teamet var punktliga, noggranna och proffsiga och levererade ett perfekt utfört takbyte som överträffade mina förväntningar. Mina varmaste rekommendationer!",
    source: "brabyggare",
    datum: "26 juni 2025",
    datumISO: "2025-06-26",
  },
  {
    name: "Björn Thews",
    tjanst: "Takbyte",
    betyg: 5,
    text: "Gediget arbete, snyggt utfört och snabbt. När problem uppstod under arbetets gång var Sands mycket snabba att bidra till rimliga lösningar, trots att det innebar en hel del merarbete för dem. Rekommenderar Sands för takbyte!",
    source: "brabyggare",
    datum: "12 juni 2025",
    datumISO: "2025-06-12",
  },
  {
    name: "Hasse",
    ort: "Sollentuna",
    tjanst: "Takläggning",
    kvm: 160,
    betyg: 5,
    text: "Jag är mycket nöjd. Över förväntan. Snabbt, noggrant och serviceinriktat.",
    source: "offerta",
    datum: "11 juni 2025",
    datumISO: "2025-06-11",
  },
  {
    name: "Lars Wiklund",
    tjanst: "Fasadmålning",
    betyg: 5,
    text: "Proffsigt från början till slut. Snabbt besök och offert. Utfört enligt spec och tidplan med hög kvalitet. Mycket noggranna.",
    source: "brabyggare",
    datum: "4 juni 2025",
    datumISO: "2025-06-04",
  },
  {
    name: "Per Hansson",
    tjanst: "Takbyte",
    betyg: 5,
    text: "Tydligt offertförfarande. Därefter bra och noggrant utfört arbete. Kan varmt rekommendera Sands Entreprenad.",
    source: "brabyggare",
    datum: "30 maj 2025",
    datumISO: "2025-05-30",
  },
  {
    name: "Hassan",
    ort: "Tullinge",
    tjanst: "Takläggning",
    kvm: 74,
    betyg: 5,
    text: "Väldigt smidigt och effektivt.",
    source: "offerta",
    datum: "23 maj 2025",
    datumISO: "2025-05-23",
  },
  {
    name: "Leif",
    ort: "Ekerö",
    tjanst: "Takläggning",
    kvm: 100,
    betyg: 5,
    text: "Min bedömning är att arbetet gjorts fackmannamässigt och enligt en offert som bra sammanfattade vad som skulle göras. Företaget har snabbt svarat på relevanta frågor.",
    source: "offerta",
    datum: "20 maj 2025",
    datumISO: "2025-05-20",
  },
  {
    name: "Björn",
    ort: "Tullinge",
    tjanst: "Takomläggning",
    kvm: 280,
    betyg: 5,
    text: "Kan verkligen rekommendera Sands Entreprenad för takomläggningar. Allt fungerade perfekt från offert till faktura.",
    source: "offerta",
    datum: "14 maj 2025",
    datumISO: "2025-05-14",
  },
  {
    name: "Marios",
    ort: "Haninge",
    tjanst: "Takläggning",
    kvm: 70,
    betyg: 5,
    text: "Utmärkt kommunikation och bra jobb på bara två dagar. Precis vad jag ville ha. Jag rekommenderar.",
    source: "offerta",
    datum: "23 mars 2025",
    datumISO: "2025-03-23",
  },
  {
    name: "Albin",
    ort: "Lidingö",
    tjanst: "Takläggning",
    kvm: 56,
    betyg: 5,
    text: "Snabbt, pålitligt och extremt kunniga från start till mål. Rekommenderas skarpt.",
    source: "offerta",
    datum: "5 mars 2025",
    datumISO: "2025-03-05",
  },
  {
    name: "Annika",
    tjanst: "Takbyte",
    betyg: 5,
    text: "Otroligt nöjd med takbytet! Arbetet genomfördes med professionalism och noggrannhet. Hela processen, från offert till färdigställande, gick smidigt och enligt plan. Tydlig kommunikation, trevlig personal och ett fantastiskt resultat. Rekommenderar starkt!",
    source: "brabyggare",
    datum: "18 februari 2025",
    datumISO: "2025-02-18",
  },
  {
    name: "Sture",
    tjanst: "Fasadmålning",
    betyg: 5,
    text: "Bra bemötande och offert. Arbetet utfördes på utlovad tid, snabbt och noggrant. Kunde inte varit bättre.",
    source: "brabyggare",
    datum: "15 juli 2024",
    datumISO: "2024-07-15",
  },
  {
    name: "Inge",
    ort: "Håbo",
    tjanst: "Golvläggning",
    betyg: 5,
    text: "Supertrevligt bemötande och ett bra utfört jobb!",
    source: "servicefinder",
    datum: "17 juni 2024",
    datumISO: "2024-06-17",
  },
  {
    name: "Torbjörn",
    ort: "Järfälla",
    tjanst: "Takomläggning, radhus",
    betyg: 5,
    text: "Är så imponerad! Omläggning av tak på radhus, ca 100 m2, gjordes på mindre än två dagar, inklusive ställningsarbete. Proffsigt utfört av trevliga och noggranna medarbetare. Städade dessutom upp ordentligt efter utfört arbete. Kan varmt rekommenderas!",
    source: "servicefinder",
    datum: "16 augusti 2023",
    datumISO: "2023-08-16",
  },
  {
    name: "Tommy",
    ort: "Enskede",
    tjanst: "Tegeltak, villa",
    betyg: 5,
    text: "Helt nytt tegeltak på en villa i Enskede. Ett mycket välgjort arbete, genomfört med en närmast svindlande hastighet, allt blev klart på endast tre dagar. Företaget kan varmt rekommenderas.",
    source: "brabyggare",
    datum: "15 augusti 2023",
    datumISO: "2023-08-15",
  },
  {
    name: "Gerhard",
    ort: "Järfälla",
    tjanst: "Takomläggning",
    betyg: 5,
    text: "Toppen! Utfört till full belåtenhet på superkort tid! Kan starkt rekommenderas.",
    source: "servicefinder",
    datum: "26 maj 2023",
    datumISO: "2023-05-26",
  },
  {
    name: "Stanley",
    ort: "Järfälla",
    tjanst: "Byte av vindskivor",
    betyg: 5,
    text: "Genomgående bra bemötande och en kontinuerlig dialog som uppskattades. Löste det vi sagt på ett mycket bra sätt och tog tag i nya problem som visade sig på vägen på ett föredömligt sätt. Levererade på utsatt tid och till överenskommen kostnad.",
    source: "servicefinder",
    datum: "10 januari 2023",
    datumISO: "2023-01-10",
  },
  {
    name: "Stefan",
    ort: "Lidingö",
    tjanst: "Komplett takomläggning",
    betyg: 5,
    text: "Mycket gott helhetsintryck: startade jobbet på utlovad tid, genomförde det snabbt och effektivt som planerat och städade upp bra efteråt. Priset mycket konkurrensmässigt och kvalitetsmässigt bra gjort. Jag anlitade besiktningsman som både förbesiktade och slutbesiktade, utan anmärkning.",
    source: "servicefinder",
    datum: "20 oktober 2022",
    datumISO: "2022-10-20",
  },
  {
    name: "Anette",
    ort: "Ekerö",
    tjanst: "Fasadmålning",
    betyg: 5,
    text: "Väldigt seriöst intryck från start då Andreas kom och bedömde arbetet. Målarna påbörjade arbetet en vecka tidigare än beräknat, stort plus. De var sjukt snabba, effektiva och noggranna. Vi är jättenöjda. Inte den billigaste offerten men vi betalar hellre för kvalitet. Kan verkligen rekommenderas!",
    source: "servicefinder",
    datum: "26 juni 2023",
    datumISO: "2023-06-26",
  },
  {
    name: "Carina",
    tjanst: "Fasadbyte, eternit",
    betyg: 5,
    text: "Fullständig transparens under hela projektet (fasadbyte och ombyggnad av uterum). Arbetar snabbt och effektivt, mycket lyhörd och rättar uppkomna smådetaljer utan krångel. Vi är mycket nöjda och kan varmt rekommendera Sands Entreprenad.",
    source: "brabyggare",
    datum: "13 oktober 2023",
    datumISO: "2023-10-13",
  },
  {
    name: "Anders",
    ort: "Österåker",
    tjanst: "Fasadmålning",
    betyg: 5,
    text: "Valet föll utan minsta tvekan på Sands. Andreas visade intresse för uppdraget, kom med genomtänkta förslag och var tydlig med förväntningarna. Priset låg helt i linje med mina förväntningar, inte billigast men långt ifrån dyrast. Killarna var trevliga, ordning och reda runt huset, bra säkerhetstänk och väl utfört arbete. Jag jobbar själv inom byggsektorn med upphandling, ger Sands mina varmaste rekommendationer.",
    source: "servicefinder",
    datum: "10 september 2024",
    datumISO: "2024-09-10",
  },
  {
    name: "Jonas Lif",
    tjanst: "Takomläggning",
    betyg: 5,
    text: "Redan vid första mötet fick jag ett mycket seriöst och kunnigt intryck. Jag fick direkt information om ansvarsförsäkringar, besiktning och en lista med referensprojekt, precis det man vill ha för att känna sig trygg. Jobbet utfördes mycket professionellt med löpande information och bilder. Jag är fantastiskt nöjd, från första kontakten till slutbesiktning av en oberoende besiktningsman.",
    source: "brabyggare",
    datum: "3 september 2018",
    datumISO: "2018-09-03",
  },
  {
    name: "Johan B.",
    tjanst: "Nytt tak",
    betyg: 5,
    text: "Kompetenta och duktiga hantverkare, snabbt utfört arbete. Dessutom väldigt flexibla med ändringar som kom sent från mitt håll. Från Sands ingår oberoende besiktningsman från OBM-gruppen, vilket väger tungt. Besiktningen gick igenom utan anmärkningar. Kan varmt rekommendera.",
    source: "brabyggare",
    datum: "17 mars 2018",
    datumISO: "2018-03-17",
  },
];
